baseURL = "https://runtimeterror.dev"
theme = "risotto"
title = "runtimeterror"
copyright = "© 2024 John Bowdre"
paginate = 10
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true

# Automatically add content sections to main menu
# sectionPagesMenu = "main"

[outputs]
  home = ['html', 'rss', 'json']
  section = ['html']
  taxonomy = ['html',]
  term = ['html', 'rss']

# rename rss output from index.xml to feed.xml
[outputFormats]
  [outputFormats.rss]
    mediatype = "application/rss"
    baseName = "feed"

[permalinks]
  posts = ":filename"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true
    disableInlineCSS = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.rss]
    limit = 20

  [services.twitter]
    disableInlineCSS = true

[taxonomies]
  tag = "tags"
  series = "series"

# Copied from https://gohugo.io/getting-started/configuration/#configure-minify
# Only change made is xml keepWhitespace = true
[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = false
  [minify.tdewolff]
    [minify.tdewolff.css]
      decimals = -1
      keepCSS2 = true
    [minify.tdewolff.html]
      keepConditionalComments = true
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = false
      keepWhitespace = false
    [minify.tdewolff.js]
    [minify.tdewolff.json]
    [minify.tdewolff.svg]
      decimals = -1
    [minify.tdewolff.xml]
      keepWhitespace = true