baseURL = "https://runtimeterror.dev"
theme = "risotto"
title = "runtimeterror"
paginate = 10
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
enableRobotsTXT = true
copyright = "Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International"

# Automatically add content sections to main menu
# sectionPagesMenu = "main"

[outputs]
  home = ['html', 'atom']
  section = ['html']
  taxonomy = ['html']
  term = ['html', 'atom']
  page = ['html']

# rename rss output from index.xml to feed.xml
[outputFormats]
  [outputFormats.atom]
    mediatype = "application/atom+xml"
    baseName = "feed"
		isPlainText = false

[mediatypes."application/atom+xml"]
	suffixes = ["xml"]

[permalinks]
  posts = ":filename"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true
    disableInlineCSS = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.rss]
    limit = 10

  [services.twitter]
    disableInlineCSS = true

[taxonomies]
  tag = "tags"
  category = "categories"

[minify]
  disableXML = true
  minifyOutput = true
