# [[main]]
#   identifier = "about"
#   name = "About"
#   url = "/about/"
#   weight = 10

[[main]]
  identifier = "posts"
  name = "posts"
  url = "/"
  weight = 1

[[main]]
  identifier = "categories"
  name = "categories"
  url = "/categories/"
  weight = 2

[[main]]
  identifier = "tags"
  name = "tags"
  url = "/tags/"
  weight = 3

[[main]]
  identifier = "about"
  name = "about"
  url = "/about/"
  weight = 4

[[main]]
  identifier = "virtuallypotato"
  name = "whereis virtuallypotato"
  url = "/virtuallypotato-runtimeterror/"
  weight = 100
