# [[main]]
#   identifier = "about"
#   name = "About"
#   url = "/about/"
#   weight = 10

[[main]]
  identifier = "index"
  name = "index"
  url = "/posts/"
  weight = -100

[[main]]
  identifier = "tags"
  name = "tags"
  url = "/tags/"
  weight = 100

[[main]]
  identifier = "projects"
  name = "projects"
  url = "/series/projects/"
  weight = 1

[[main]]
  identifier = "tips"
  name = "tips"
  url = "/series/tips/"
  weight = 1

[[main]]
  identifier = "vra8"
  name = "vra8"
  url = "/series/vra8/"
  weight = 1

[[main]]
  identifier = "scripts"
  name = "scripts"
  url = "/series/scripts/"
  weight = 1
