noindex = false

usePageBundles = true

mainSections = ["posts"]

[theme]
palette = "runtimeterror"

# Sidebar: about/bio
[about]
title = "runtimeterror"
logo = "images/broken-computer.svg"
taglines = [
  "better living through less shitty code",
  "bugs are like onions, they have layers",
  "bugs, uh, find a way",
  "creating new and exciting bugs",
  "houston, we have a bug",
  "i ain't afraid of no code",
  "i see null pointers",
  "i'm not a real programmer",
  "keep your friends close, but your breakpoints closer",
  "may the code be with you",
  "ship things and breakfast",
  "there's no place like $HOME",
  "tonight we test in prod",
  "why did it have to be bugs",
  "you can't handle the exception",
  "i'm the one who debugs",
  "calm that panicked kernel",
  "i opened vi and i can't get out",
  "[ESC]:q!",
  "i'd tell you a udp joke but",
  "that's a layer 8 problem",
  "while (true) { bugs++; }",
  "from the creators of 'undefined is not a function'",
  "from chatgpt with bugs",
  "invalid username or password",
  "no such file or directory",
  "segmentation fault (core dumped)",
  "the system is down",
  "read-only file system",
  "kernel panic - not syncing: attempted to kill init",
  "out of memory: kill process or sacrifice child",
  "directory not empty",
  "broken pipe",
  "permission denied (publickey)",
  "error: could not stat or open file",
  "write error: no space left on device",
  "bad file descriptor",
  "resource temporarily unavailable",
  "unable to open display",
  "invalid option",
  "host key verification failed",
  "file descriptor in bad state",
  "connection reset by peer",
  "stale nfs file handle",
  "put that in your tar pipe and send it",
  "you're not in the sudoers file. this incident will be reported",
  "sudo make me a sandwich",
  "syntax error: unexpected end of file",
  "syntax error: unexpected token",
  "variable has already been declared",
  "unexpected token",
  "function does not return a value",
  "division by zero",
  "pointer arithmetic on non-pointer type",
  "invalid assignment",
  "undefined reference to function",
  "array index out of bounds",
  "class/struct has no member named undefined",
  "cannot access private member declared in class",
  "cyclic dependency detected",
  "expression has no effect",
  "i'm in ur codez, fixin ur bugz",
  "destructor cannot be overloaded",
  "converting caffeine to bugs which sometimes work",
]

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/jbowdre"

[[socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:ops@runtimeterror.dev"
