noindex = false

usePageBundles = true

mainSections = ["posts"]

[theme]
palette = "runtimeterror"

# Sidebar: about/bio
[about]
title = "runtimeterror"
logo = "images/broken-computer.svg"
taglines = [
  "better living through less shitty code",
  "bugs are like onions, they have layers",
  "bugs, uh, find a way",
  "creating new and exciting bugs",
  "houston, we have a bug",
  "i ain't afraid of no code",
  "i see null pointers",
  "i'm not a real programmer",
  "keep your friends close, but your breakpoints closer",
  "may the code be with you",
  "ship things and breakfast",
  "there's no place like localhost",
  "tonight we test in prod",
  "why did it have to be bugs",
  "you can't handle the exception",
]

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/jbowdre"

[[socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:ops@runtimeterror.dev"
