noindex = false

usePageBundles = true

mainSections = ["posts"]

[theme]
palette = "runtimeterror"

# Sidebar: about/bio
[about]
title = "runtimeterror"
logo = "images/broken-computer.svg"
taglines = [
  "[ESC]:q!",
  "array index out of bounds",
  "bad file descriptor",
  "better living through less shitty code",
  "broken pipe",
  "bugs are like onions, they have layers",
  "bugs, uh, find a way",
  "calm that panicked kernel",
  "cannot access private member declared in class",
  "class/struct has no member named undefined",
  "connection reset by peer",
  "converting caffeine to bugs which sometimes work",
  "creating new and exciting bugs",
  "cyclic dependency detected",
  "destructor cannot be overloaded",
  "directory not empty",
  "division by zero",
  "error: could not stat or open file",
  "expression has no effect",
  "file descriptor in bad state",
  "from chatgpt with bugs",
  "from the creators of 'undefined is not a function'",
  "function does not return a value",
  "host key verification failed",
  "houston, we have a bug",
  "i ain't afraid of no code",
  "i opened vi and i can't get out",
  "i see null pointers",
  "i'd tell you a udp joke but",
  "i'm in ur codez, fixin ur bugz",
  "i'm not a real programmer",
  "i'm the one who debugs",
  "invalid assignment",
  "invalid option",
  "invalid username or password",
  "keep your friends close, but your breakpoints closer",
  "kernel panic - not syncing: attempted to kill init",
  "may the code be with you",
  "no such file or directory",
  "out of memory: kill process or sacrifice child",
  "permission denied (publickey)",
  "pointer arithmetic on non-pointer type",
  "put that in your tar pipe and send it",
  "read-only file system",
  "resource temporarily unavailable",
  "segmentation fault (core dumped)",
  "ship things and breakfast",
  "stale nfs file handle",
  "sudo make me a sandwich",
  "syntax error: unexpected end of file",
  "syntax error: unexpected token",
  "that's a layer 8 problem",
  "the system is down",
  "there's no place like $HOME",
  "tonight we test in prod",
  "unable to open display",
  "undefined reference to function",
  "unexpected token",
  "variable has already been declared",
  "while (true) { bugs++; }",
  "why did it have to be bugs",
  "write error: no space left on device",
  "you can't handle the exception",
  "you're not in the sudoers file. this incident will be reported",
]

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/jbowdre"

[[socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:ops@runtimeterror.dev"
