[build]
  command = """
  hugo --minify
  npm -i @torchlight-api/torchlight-cli
  npx torchliight
  """
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.111.3"

[context.production]
  command = "hugo"

[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404